### ISSUE TITLE
IISWC Tutorial Question: ./scripts/build-onnx-inference.sh

### ISSUE THREAD

**Issue by Teut0nic** [ucb-bar/gemmini#236]
Hello,

I'm trying to follow the Gemmini IISWC Tutorial.  They use a /tutorial directory that I do not have.  I'm trying to perform the following steps without the tutorial directory and am getting the following error when trying to run ./scripts/build-onnx-inference.sh
I tried running the command while in superuser mode, and still getting errors.

user:~/chipyard/generators/gemmini$ ./scripts/build-onnx-inference.sh
./scripts/build-onnx-inference.sh: line 3: cd: /root/chipyard/generators/gemmini/software/onnxruntime-riscv/: Permission denied
./scripts/build-onnx-inference.sh: line 5: ./build.sh: No such file or directory
./scripts/build-onnx-inference.sh: line 6: cd: ./systolic_runner/imagenet_runner/: No such file or directory
./scripts/build-onnx-inference.sh: line 7: ./build.sh: No such file or directory

Regards,
Matt

**Comment by hngenc** [comment]
Try [this version](https://github.com/ucb-bar/gemmini/blob/dev/scripts/build-onnx-inference.sh) of the "build-onnx-inference.sh" script (from Gemmini's "dev" branch). That should correct the path so that it works on all systems.

(We'll merge this into Gemmini's `master` branch soon.)

I'm closing this issue for now, but feel free to re-open it if you still have issues.
